fullnameOverride: "test-app"
# namespace: test1

deployment:
  containers:
  - name: container-namez
    image:
      repository: gcr.io/google_containers/echoserver
      tag: "1.10"

    ports:
    - name: http
      protocol: TCP
      containerPort: 8080
      servicePort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-external
    # kubernetes.io/tls-acme: "true"
  paths:
    - path: /
      servicePort: http
  hosts:
    - chart-example.local
  tls:
  - secretName: chart-example-tls
    hosts:
    - chart-example.local
