#
# Deployment variables
#
#
# Deployment variables
#
deployment:
  containers:
  - name: container-name
    image:
      repository: gcr.io/google_containers/echoserver
      tag: "1.10"
      pullPolicy: IfNotPresent
    command: []
    # - foo
    # - bar
    args: []
    # - foo2
    # - bar2

    env:
      # Values in the base environment will be applied across all environments, and are NOT expected to be overridden
      # on a per-environment basis
      base: []
      # - name: foo
      #   value: bar

      # Values in perEnv will be local to an environment
      perEnv: []
      # - name: bar
      #   value: foo

    ports: []
    # - name: http
    #   protocol: TCP
    #   containerPort: 80
    #   servicePort: 8080

    livenessProbe: {}
      # httpGet:
      #   path: /
      #   port: http
    readinessProbe: {}
      # httpGet:
      #   path: /
      #   port: http
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi

    volumeMounts:
    # name must match the volume name below
    - name: secret-volume
      mountPath: /etc/secret-volume

#
# Volumes - to be attached to the pod.
#
# This only attaches the volume to the pod.  To use it, you have to add a "volumeMounts" to
# a container on the location to mount it to or add it the content to the "env" of a container
# in the pod.
#
volumes:
- name: secret-volume
  secret:
    secretName: test-secret
# - name: config-volume
#   configMap:
#     # Provide the name of the ConfigMap containing the files you want
#     # to add to the container
#     name: special-config
