fullnameOverride: "test-app"
# namespace: test1

deployment:
  containers:
  - name: container-namez
    image:
      repository: gcr.io/google_containers/echoserver
      tag: "1.10"

    ports:
    - name: http
      protocol: TCP
      containerPort: 8080
      servicePort: 8080

serviceaccount:
  enabled: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/my-role
  labels: {}
