apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "query-exporter.fullname" . }}-cert-db
  labels:
    {{ include "query-exporter.labels" . | nindent 4 }}
data:
 query-exporter-cert-db.pem: |-
  {{ tpl .Values.cert_db . | nindent 4 }}
