---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "query-exporter.fullname" . }}
  labels:
    {{- include "query-exporter.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "query-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "query-exporter.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "query-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{- range .Values.image.command }}
            - {{ . }}
          {{- end }}
          {{- if .Values.env }}
          env:
          {{- range $key, $value :=  .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if or .Values.existingSecret .Values.secrets }}
          envFrom:
            {{- if .Values.existingSecret }}
            - secretRef:
                name: {{ .Values.existingSecret }}
            {{- else if and .Values.secrets (not .Values.existingSecret)}}
            - secretRef:
                name: {{ include "query-exporter.fullname" . }}
            {{- else }}
            {{- end }}
          {{- end }}
          ports:
          - containerPort: 9560
            protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources: 
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              readOnly: true
              name: {{ include "query-exporter.fullname" . }}
        {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
        {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "query-exporter.fullname" . }}
          configMap:
            name: {{ include "query-exporter.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
    {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
