{{- if and .Values.secrets (not .Values.existingSecret) -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "query-exporter.fullname" . }}
  labels:
    {{- include "query-exporter.labels" . | nindent 4 }}
data:
  {{- range $key, $value :=  .Values.secrets }}
  {{ $key }}: {{ $value | b64enc  | quote }}
  {{- end }}
{{- end }}
