{{- if .Values.serviceaccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
{{ toYaml .Values.serviceaccount.annotations | indent 4 }}
  labels:
{{ toYaml .Values.serviceaccount.labels | indent 4 }}
  name: {{ include "standard-application.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
{{- end }}
