{{- if .Values.statefulset.enable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "standard-application.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    helm.sh/chart: {{ include "standard-application.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.selector: {{ include "standard-application.fullname" . }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.selector: {{ include "standard-application.fullname" . }}
  serviceName: {{ include "standard-application.fullname" . }}
  
  {{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.deployment.annotations | indent 8 }}
      labels:
        app.selector: {{ include "standard-application.fullname" . }}
        {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceaccount.enabled }}
      serviceAccountName: {{ include "standard-application.fullname" . }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- if .Values.containerSpecOptions }}
{{ toYaml .Values.containerSpecOptions | indent 6 }}
      {{- end }}


      {{- if .Values.deployment.enableInitContainer }}
      # enabling initContainer(s)
      initContainers:
{{ toYaml .Values.deployment.initContainers | indent 8 }}
      {{- end }}

      containers:

        {{- range $index, $container := .Values.deployment.containers }}
        # Container {{ $index }} - {{ $container.name }}
        - name: {{ $container.name }}
          image: "{{ $container.image.repository }}:{{ $container.image.tag }}"
          imagePullPolicy: {{ $container.image.pullPolicy }}
          {{- if $container.command }}
          command:
{{ toYaml $container.command | indent 10 }}
          {{- end }}
          {{- if $container.args }}
          args:
{{ toYaml $container.args | indent 10 }}
          {{- end }}

          {{- if $container.env }}
          {{- if or (gt (len $container.env.base) 0) (gt (len $container.env.perEnv) 0) }}
          env:
          {{- if gt (len $container.env.base) 0 }}
          # base
{{ toYaml $container.env.base | indent 10 }}
          {{- end }}
          {{- if gt (len $container.env.perEnv) 0 }}
          # perEnv
{{ toYaml $container.env.perEnv | indent 10 }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if $container.envFrom }}
          envFrom:
{{ toYaml $container.envFrom | indent 10 }}
          {{- end }}

          # START: ports
          {{- if $container.ports }}
          ports:
          {{- range $index, $item := $container.ports }}
          # Port {{ $index }}
          - containerPort: {{ $item.containerPort }}
            protocol: {{ $item.protocol }}
            name: {{ $item.name }}
          {{- end }}
          {{- end }}
          # END: ports
          {{- if $container.livenessProbe }}
          livenessProbe:
{{ toYaml $container.livenessProbe | indent 12 }}
          {{- end }}
          {{- if $container.readinessProbe }}
          readinessProbe:
{{ toYaml $container.readinessProbe | indent 12 }}
          {{- end }}
          resources:
            {{- toYaml $container.resources | nindent 12 }}

          securityContext:
            {{- toYaml $container.securityContext | nindent 12 }}

          {{- if $container.volumeMounts }}
          # volumeMounts
          volumeMounts:
{{ toYaml $container.volumeMounts | indent 12 }}
          {{- end }}

        {{- end }}


      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:      
      {{- range .Values.deployment.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      {{- with .Values.volumes }}
      # Volumes
      volumes:
{{- toYaml . | nindent 8 }}
      {{- end }}


  {{- with .Values.volumeClaimTemplates }}
  # volumeClaimTemplates
  volumeClaimTemplates:
{{- toYaml . | nindent 2 }}
      {{- end }}

{{- end }}