apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- with .Values.service.ports }}
  {{- toYaml . | nindent 2 }}
{{- end -}}
  selector:
    app: spire-server
